#include "engine/scene/serialization/SceneLoader.h"

#include "engine/assets/manager/AssetManager.h"
#include "engine/render/resources/MeshAsset.h"
#include "engine/scene/components/BrushComponent.h"   // F2H11
#include "engine/scene/components/Components.h"
#include "engine/scene/core/Entity.h"
#include "engine/scene/core/Scene.h"
#include "engine/scene/serialization/SceneSerializer.h"
#include "engine/scene/serialization/TilePersistence.h"

#include <utility>
#include <vector>

namespace Mood::SceneLoader {

Entity applyOneEntity(const SavedEntity& se,
                       Scene& scene,
                       AssetManager& assets) {
    // Reemplazo de entidades auto-generadas: si esta SavedEntity tiene
    // un tag que `rebuildSceneFromMap` también genera ("Floor",
    // "Tile_X_Y"), Y ya existe una entidad con ese mismo tag en el
    // scene (caso típico: rebuildSceneFromMap creó un default que este
    // load debe reemplazar con los valores persistidos), la destruimos
    // antes de crear la nueva. Sin esto, el scene queda con DOS
    // entidades de mismo tag y comportamiento degenerado:
    // - Floor duplicado: dos planos de tamaño 48m × 48m superpuestos
    //   → fillrate brutal, percepción de freeze.
    // - Tile duplicado: dos cubos en mismo lugar.
    //
    // **Limitado a tags auto-generados**: otros tags pueden ser
    // duplicados legítimamente (ej. múltiples "CajaFisica", "Multi" en
    // redo de comandos batch). Reemplazar TODOS rompería esos casos.
    u32 tileX = 0, tileY = 0;
    const bool isAutoGeneratedTag =
        (se.tag == "Floor") ||
        parseTileCoords(se.tag.c_str(), tileX, tileY);
    if (isAutoGeneratedTag) {
        Entity existing;
        scene.forEach<TagComponent>([&](Entity ex, TagComponent& tag) {
            if (tag.name == se.tag && !static_cast<bool>(existing)) {
                existing = ex;
            }
        });
        if (static_cast<bool>(existing)) {
            scene.destroyEntity(existing);
        }
    }

    Entity e = scene.createEntity(se.tag);
    auto& t = e.getComponent<TransformComponent>();
    t.position      = se.position;
    t.rotationEuler = se.rotationEuler;
    t.scale         = se.scale;

    {
        if (se.meshRenderer.has_value()) {
            const auto& mr = *se.meshRenderer;
            const MeshAssetId meshId = assets.loadMesh(mr.meshPath);
            // Hito 17 upgrader: el campo `materials` puede contener
            // paths de `.material` (v7) o paths de texturas (v6 con
            // back-compat). Detectamos por extension.
            std::vector<MaterialAssetId> mats;
            mats.reserve(mr.materials.size());
            for (const auto& path : mr.materials) {
                if (path.empty()) {
                    mats.push_back(assets.missingMaterialId());
                    continue;
                }
                const bool isMaterial =
                    path.size() >= 9 &&
                    path.compare(path.size() - 9, 9, ".material") == 0;
                if (isMaterial) {
                    mats.push_back(assets.loadMaterial(path));
                } else {
                    // Cada entidad persistida con texture-path obtiene su
                    // PROPIO material instance (createMaterialFromTexture,
                    // no loadMaterialFromTexture cacheado). Asi editar el
                    // tint de un cubo cargado del .moodmap no contagia a
                    // los demas cubos que tenian la misma textura.
                    const TextureAssetId tex = assets.loadTexture(path);
                    mats.push_back(assets.createMaterialFromTexture(tex));
                }
            }
            e.addComponent<MeshRendererComponent>(meshId, std::move(mats));

            // Hito 22 fix arrastrado del Hito 19: si el mesh trae
            // skeleton + clips, auto-agregar Animator + Skeleton igual
            // que `processViewportMeshDrop`. Sin esto, un Fox.glb
            // guardado en `.moodmap` reaparece en bind pose porque
            // esos dos componentes no se serializan.
            const MeshAsset* asset = assets.getMesh(meshId);
            if (asset != nullptr && asset->hasSkeleton()
                && !asset->animations.empty()) {
                AnimatorComponent anim{};
                anim.clipName = "";   // primer clip
                anim.playing  = true;
                anim.loop     = true;
                e.addComponent<AnimatorComponent>(anim);
                e.addComponent<SkeletonComponent>(SkeletonComponent{});
            }
        }

        if (se.light.has_value()) {
            const auto& sl = *se.light;
            LightComponent lc{};
            lc.type = (sl.type == "directional")
                ? LightComponent::Type::Directional
                : LightComponent::Type::Point;
            lc.color       = sl.color;
            lc.intensity   = sl.intensity;
            lc.radius      = sl.radius;
            lc.direction   = sl.direction;
            lc.enabled     = sl.enabled;
            lc.castShadows = sl.castShadows;
            e.addComponent<LightComponent>(lc);
        }

        if (se.rigidBody.has_value()) {
            const auto& srb = *se.rigidBody;
            RigidBodyComponent rb{};
            if (srb.type == "static")         rb.type = RigidBodyComponent::Type::Static;
            else if (srb.type == "kinematic") rb.type = RigidBodyComponent::Type::Kinematic;
            else                              rb.type = RigidBodyComponent::Type::Dynamic;
            if (srb.shape == "sphere")        rb.shape = RigidBodyComponent::Shape::Sphere;
            else if (srb.shape == "capsule")  rb.shape = RigidBodyComponent::Shape::Capsule;
            else                              rb.shape = RigidBodyComponent::Shape::Box;
            rb.halfExtents = srb.halfExtents;
            rb.mass        = srb.mass;
            rb.friction    = srb.friction;   // Hito 34 A
            e.addComponent<RigidBodyComponent>(rb);
        }

        if (se.environment.has_value()) {
            const auto& s = *se.environment;
            EnvironmentComponent env{};
            env.skyboxPath = s.skyboxPath;
            if      (s.fogMode == "linear") env.fogMode = 1;
            else if (s.fogMode == "exp")    env.fogMode = 2;
            else if (s.fogMode == "exp2")   env.fogMode = 3;
            else                            env.fogMode = 0;
            env.fogColor       = s.fogColor;
            env.fogDensity     = s.fogDensity;
            env.fogLinearStart = s.fogLinearStart;
            env.fogLinearEnd   = s.fogLinearEnd;
            env.exposure       = s.exposure;
            if      (s.tonemapMode == "reinhard") env.tonemapMode = 1;
            else if (s.tonemapMode == "aces")     env.tonemapMode = 2;
            else                                  env.tonemapMode = 0;
            env.iblIntensity   = s.iblIntensity;
            e.addComponent<EnvironmentComponent>(env);
        }

        // Hito 29: ParticleEmitterComponent. Re-resolvemos el id de
        // textura via path logico (los ids son volatiles entre sesiones).
        if (se.particleEmitter.has_value()) {
            const auto& s = *se.particleEmitter;
            ParticleEmitterComponent em{};
            em.emitRate     = s.emitRate;
            em.lifetimeMin  = s.lifetimeMin;
            em.lifetimeMax  = s.lifetimeMax;
            em.velocityMin  = s.velocityMin;
            em.velocityMax  = s.velocityMax;
            em.sizeStart    = s.sizeStart;
            em.sizeEnd      = s.sizeEnd;
            em.colorStart   = s.colorStart;
            em.colorEnd     = s.colorEnd;
            em.gravityFactor = s.gravityFactor;
            em.maxParticles = s.maxParticles;
            em.emitting     = s.emitting;
            em.additive     = s.additive;
            em.localSpace   = s.localSpace;
            // Hito 37 C: shape de emision (default Point).
            using ES = ParticleEmitterComponent::EmissionShape;
            if      (s.emissionShape == "box")    em.emissionShape = ES::Box;
            else if (s.emissionShape == "sphere") em.emissionShape = ES::Sphere;
            else if (s.emissionShape == "disc")   em.emissionShape = ES::Disc;
            else if (s.emissionShape == "cone")   em.emissionShape = ES::Cone;
            else                                   em.emissionShape = ES::Point;
            em.emissionShapeSize = s.emissionShapeSize;
            em.emissionConeAxis  = s.emissionConeAxis;
            em.texture = s.texturePath.empty()
                ? assets.missingTextureId()
                : assets.loadTexture(s.texturePath);
            e.addComponent<ParticleEmitterComponent>(em);
        }

        // Hito 33: TriggerComponent. Solo restauramos halfExtents; el flag
        // runtime playerInside arranca en false (TriggerSystem lo redetecta
        // al primer update si el char ya cae dentro del AABB).
        if (se.trigger.has_value()) {
            const auto& s = *se.trigger;
            TriggerComponent tc{};
            tc.halfExtents = s.halfExtents;
            e.addComponent<TriggerComponent>(tc);
        }

        // Hito 24: ScriptComponent + overrides. El script se carga
        // perezosamente desde `ScriptSystem` (mtime-based), aca solo
        // adjuntamos el path + overrides; `engine.exposed` los lee en
        // el chunk top-level cuando el sistema haga el primer load.
        if (se.script.has_value()) {
            const auto& s = *se.script;
            e.addComponent<ScriptComponent>(s.path);
            auto& sc = e.getComponent<ScriptComponent>();
            sc.overrides = s.overrides;
        }

        if (!se.prefabPath.empty()) {
            e.addComponent<PrefabLinkComponent>(se.prefabPath);
        }
    }
    return e;
}

void applyEntitiesToScene(const SavedMap& saved,
                          Scene& scene,
                          AssetManager& assets) {
    for (const auto& se : saved.entities) {
        applyOneEntity(se, scene, assets);
    }

    // F2H11: aplicar brushes CSG. Cada SavedBrush -> nueva entidad con
    // TagComponent + TransformComponent (los crea createEntity) +
    // BrushComponent. Reconstruimos `Csg::Brush` directamente desde
    // los planos persistidos: los SavedBrushFace ya contienen normal y
    // distance en world space (las que makeBoxBrush escribio al
    // serializar). dirty=true fuerza al SceneRenderer a regenerar la
    // mesh en el primer frame.
    for (const auto& sb : saved.brushes) {
        Entity e = scene.createEntity(sb.tag);
        auto& t = e.getComponent<TransformComponent>();
        t.position      = sb.position;
        t.rotationEuler = sb.rotationEuler;
        t.scale         = sb.scale;

        BrushComponent bc;
        bc.brush.faces.reserve(sb.faces.size());
        for (const auto& sf : sb.faces) {
            Csg::BrushFace face;
            face.plane.normal   = sf.normal;
            face.plane.distance = sf.distance;
            face.materialIndex  = sf.materialIndex;
            bc.brush.faces.push_back(face);
        }
        bc.brush.localAabb = Csg::computeBrushAabb(bc.brush);
        // Material por path logico. "" significa "sin material"
        // (slot 0 = look blank gris).
        bc.material = sb.materialPath.empty()
            ? 0u : assets.loadMaterial(sb.materialPath);
        bc.dirty = true;
        e.addComponent<BrushComponent>(std::move(bc));
    }
}

} // namespace Mood::SceneLoader
